### ISSUE TITLE
控件领养登记

### ISSUE THREAD

**Issue by jinzhubaofu** [ecomfe/moye#37]
目前`moye`有以下控件, 欢迎大家前来领养:

~~按钮 Button~~
~~日历控件 Calendar ~~
~~输入框 TextBox~~
~~城市选择 City~~
~~分页控件 Pager~~
~~单选/复选 Raido / Checkbox~~
~~浮层提示 Tip + 浮动提示 FloatTip~~
~~下拉选项 Select~~
~~图片延迟加载 Lazy~~
~~选 项 卡 Tabs~~
~~对 话 框 Dialog~~
~~星号评级 Rating~~
~~图片轮播 Slider~~

----------------

补充一些

图片上传 PicUploader
滚 动 条 ScrollBar
农历控件 Lunar
回到顶部 BackTop
表单 Form
标签 Tag

> 呃, 如果无人领养, 控件就要被移除了呢~

**Comment by deodeng** [comment]
图片轮播 Slider
denglingbo

**Comment by oddjohn** [comment]
星号评级 Rating 
陈志安

**Comment by kaivean** [comment]
Tabs  吴开放

**Comment by zhangzhiqiang37** [comment]
城市选择 City
张志强zhangzhiqiang37

**Comment by jinzhubaofu** [comment]
Select lupengyu

**Comment by michaelliu90316** [comment]
浮层提示 Tip + 浮动提示 FloatTip   liulangyu

**Comment by mySunShinning** [comment]
分页控件 Pager

**Comment by mySunShinning** [comment]
wuqi

**Comment by ccksfh** [comment]
对 话 框 Dialog

邱斯琪

**Comment by The-only** [comment]
单选/复选 Raido / Checkbox  邓小红

**Comment by huanghuiquan** [comment]
图片延迟加载 Lazy
黄辉泉

**Comment by liuxuanzy** [comment]
领养日历控件，宗宇

**Comment by jinzhubaofu** [comment]
TextBox 逯鹏宇

**Comment by zwsf** [comment]
scrollbar 卢文龙
