### ISSUE TITLE
City控件需求汇总

### ISSUE THREAD

**Issue by zhangzhiqiang37** [ecomfe/moye#38]
百度教育 http://jiaoyu.baidu.com/
![image](https://cloud.githubusercontent.com/assets/5220712/5972615/a7cc33f0-a897-11e4-8839-b37f6de9def6.png)

百度汽车 http://car.baidu.com/
![image](https://cloud.githubusercontent.com/assets/5220712/5972639/e6f6dbfc-a897-11e4-9926-c94fa800f211.png)

百度租车 zuchzuche.baidu.com
![image](https://cloud.githubusercontent.com/assets/5220712/5972704/c9b95cc6-a898-11e4-8a58-8157797a6699.png)

**Comment by jinzhubaofu** [comment]
来自百度财富大搜索卡片的需求

![image](https://cloud.githubusercontent.com/assets/811195/6074487/8ff4e804-adfa-11e4-8757-35c4bd6519a5.png)

**Comment by zhangzhiqiang37** [comment]
最小功能汇总：

1、有一个容器（input等）来放置选中的城市，可设置默认值
2、拥有一个浮层，可包含城市信息，城市信息可进行分组，可设置默认选中组
3、可选是否使用默认城市
4、可以屏蔽城市，可以添加自定义城市
5、控件支持注册pick（选择城市触发），beforeShow（浮层出现触发）、hide（选择城市后浮层隐藏触发）事件

**Comment by zhangzhiqiang37** [comment]
另外，今天重新看了，我前面整理的使用场景都没有用到moye的控件，@jinzhubaofu 补充的才是

**Comment by zhangzhiqiang37** [comment]
属性&接口&事件：

属性：
{(string | HTMLElement)} main
{(string | HTMLElement)} target
{number} index
{boolean} autoFill
{?string} hideCities

接口：
fill
setTarget

事件：
pick
beforeShow
hide

**Comment by jinzhubaofu** [comment]
City应该是一个输入控件，应当支持`getValue()`和`setValue()`，以及事件`change`
