### ISSUE TITLE
Tip控件需求汇总

### ISSUE THREAD

**Issue by michaelliu90316** [ecomfe/moye#39]
诚信V标：[http://koubei.baidu.com/s/baidu.com]()
![v](https://cloud.githubusercontent.com/assets/1811842/5991990/d1f80788-aa4c-11e4-8f23-5933a724b040.png)

---
百度口碑：[http://koubei.baidu.com/s/baidu.com?tab=truth]()
![click_tip](https://cloud.githubusercontent.com/assets/1811842/5991991/03f22d2c-aa4d-11e4-91cc-3d9c1bc0ed01.png)

**Comment by michaelliu90316** [comment]
基本功能
1. 有一个浮层
2. 浮层触发方式：`hover` 、 `click` ( `Tip` 不需要 `static` )
3. 浮层隐藏显示可 `自动` 和 `手动` 触发
4. 支持浮层位置动态计算
5. 可设置浮层内容
6. 有一个 `可选箭头` ，标识方向

**Comment by michaelliu90316** [comment]
## Tip接口
可继承于 `Popup`，`Popup` 部分功能可能需要重构
`title` 相关的看以后需求

### 属性
1. {(string | Array)} triggers
2. {(string | HTMLElement)} target
3. {string} content
4. {(boolean | string)} arrow
5. {boolean} disabled
6. {Object} offset
7. {string} mode
8. {number} showDelay
9. {number} hideDelay

### 方法
1. show()
2. hide()
3. isVisible()
4. setContent()
5. locate()          // 需要暴露，有重新计算位置的需求
6. refresh()

### 事件
1. `beforeshow`
2. `show` / `hide` 
3. `click`

**Comment by jinzhubaofu** [comment]
之前我和大佛讨论过这两个控件, 有两个建议:

1. 建议将 `Tip` 和 `FloatTip` 合并为 `Tip`. 移除 `FloatTip`, 添加 `Tip` 的 `static` 模式. 
2. 目前`Tip`中的定位功能与`Popup`重复, 建议 `Tip` 直接继承 `Popup`; 因此, 也将`Popup`控件也划到你这里啦.

**Comment by michaelliu90316** [comment]
好的，之前也想把 `FloatTip` 干掉~
