### ISSUE TITLE
单选/复选 Raido / Checkbox需求汇总

### ISSUE THREAD

**Issue by The-only** [ecomfe/moye#40]
Radio: 百度汽车：http://car.baidu.com/
![image](https://cloud.githubusercontent.com/assets/3883322/5995522/5671fe3c-aad0-11e4-94e7-a311345e3bcd.png)
百度健康： http://jiankang.baidu.com/Drug/index
![image](https://cloud.githubusercontent.com/assets/3883322/5995527/6927dc72-aad0-11e4-815d-826964d0a9e4.png)
百度教育：http://jiaoyu.baidu.com/query/juhe?categoryID=010202
![image](https://cloud.githubusercontent.com/assets/3883322/5995529/7403ec9e-aad0-11e4-8c2c-d9a47bec67e6.png)
Checkbox: 百度财富：http://caifu.baidu.com/fund?tn=NONE&zt=self&fr=-&qid=1422594395030340 
![image](https://cloud.githubusercontent.com/assets/3883322/5995530/814a402e-aad0-11e4-96cc-bfdc9f7b2f40.png)

**Comment by kaivean** [comment]
百度生活服务：http://hunqing.baidu.com/hunqingtuangou?zt=midpagetab&F_tagProv=0
![image](https://cloud.githubusercontent.com/assets/3810606/5996354/d322768e-aae2-11e4-9ce7-9f31fe88acd9.png)

**Comment by The-only** [comment]
百度财富：http://caifu.baidu.com/fund?tn=NONE&zt=self&fr=-&qid=1422594395030340
![111](https://cloud.githubusercontent.com/assets/3883322/6054470/775e2530-ad28-11e4-9e15-797473b62b83.jpg)

**Comment by The-only** [comment]
复选单选最小功能集合确定为以上两种类型效果：背景颜色型、icon型（通过添加icon实现）。
