### ISSUE TITLE
Dialog 对话框控件需求汇总

### ISSUE THREAD

**Issue by ccksfh** [ecomfe/moye#42]

**Comment by ccksfh** [comment]
![weigou-feedback](https://cloud.githubusercontent.com/assets/4878697/6053857/04070974-ad20-11e4-88b7-1599d3eb8ad8.JPG)

**Comment by chriswong** [comment]
DialogFactory 去掉，alert/confirm 这些方法直接挂到 Dialog 类上

**Comment by chriswong** [comment]
DialogFactory 去掉，alert/confirm 这些方法直接挂到 Dialog 类上

**Comment by ccksfh** [comment]
额。。上面的反馈貌似是属于textbox控件范畴的。。对dialog的理解有误。。

**Comment by jinzhubaofu** [comment]
Dialog需要能支持在其内部嵌套各种其他控件, 这应该算一个需求点.

**Comment by ccksfh** [comment]
(https://cloud.githubusercontent.com/assets/4878697/6160389/0b1106fc-b29d-11e4-9498-549ba7ea7487.JPG)

**Comment by ccksfh** [comment]
![a4ae2d9d-d421-4893-bbe9-7de67b984778](https://cloud.githubusercontent.com/assets/4878697/6161330/3a1d3e2c-b2aa-11e4-978e-9e10e1b4e44c.JPG)
![e0d08ec8-967b-4db6-bf39-793f5fd69e57](https://cloud.githubusercontent.com/assets/4878697/6161335/47b0a498-b2aa-11e4-8e75-ef5b2bb2f55c.JPG)
