### ISSUE TITLE
Rating 星号评级控件需求汇总

### ISSUE THREAD

**Issue by oddjohn** [ecomfe/moye#43]

**Comment by oddjohn** [comment]
百度教育评论：
![image](https://cloud.githubusercontent.com/assets/5519703/6100328/d06a702a-b048-11e4-8fcb-2f2e27e01505.png)

**Comment by oddjohn** [comment]
百度健康（这个地方用的不是moye的Rating组件）：
![image](https://cloud.githubusercontent.com/assets/5519703/6100568/f6b9d2f8-b04c-11e4-812e-9d080fe99fb1.png)

**Comment by oddjohn** [comment]
补充：
Rating组件除了用星号，还能支持❤型这样的评级。
最小功能集合：
1. 鼠标hover状态点亮的星星跟随鼠标位置,并提供hover的回掉方法；
2. 鼠标选择之后，允许用户做一些操作，如提示之类的；
3. 提供多种皮肤供选择，包括扁平化，拟物化等风格。

# Rating组件属性与方法定义

## 属性
1. {number} max
2. {number} value
3. {string} skin
4. {bool} disabled
5. {bool} readonly

## 接口
1. {number} getValue()
2. {number} setValue()
3. disable()
4. enable()


## 事件
change
hover

// 是否可增加一种仅做展示的，支持小数点后一位的数字的评分功能

**Comment by jinzhubaofu** [comment]
仅做展示的评分控件是有需求的呀, 例如在百度财富这里有一个.

http://caifu.baidu.com/fund?tn=NONE&zt=self&fr=-&qid=1423489757455550

![image](https://cloud.githubusercontent.com/assets/811195/6107415/acaca920-b0a5-11e4-80ea-4ffeabd66e0e.png)

我这里没有做成`moye`的控件, 因为只有一个展现功能, 只有`html`和`css`就可以了.

不过, 我们后续可以把这种情况也包含在moye中, 也就是提供后端预渲染功能.

例如, 我们会提供一个`smarty`函数给大家来使用: 

 ```smarty
{%Rating data=$ratingConf%}
```

或者是提供`etpl`的`target`

```
<!-- use: Rating(data=${ratingConf}) -->
```

可以生成一个`Rating`的必要dom结构和相应的样式

```html
<div class="ui-rating"> ... </div.
```

后续我们会安排一弹任务让大家来完成后端预渲染功能.

**Comment by oddjohn** [comment]
我考虑的是这种不是整1或整0.5的一种展示状态，例如下面这种
![image](https://cloud.githubusercontent.com/assets/5519703/6107637/83f1c586-b0a7-11e4-904d-03bb8f625401.png)

**Comment by michaelliu90316** [comment]
`setValue`  会触发 `change` 事件么？

**Comment by oddjohn** [comment]
`setValue`就不触发`change`了吧，不然在`change`里面`setValue`那不是停不下来？

**Comment by michaelliu90316** [comment]
我这边是有这样的需求的：需要提供接口，可以设置星星的选中，调用的时候，可以选择触发或者不触发`change` 
[http://koubei.baidu.com/w/tmall.com]()

**Comment by jinzhubaofu** [comment]
@oddjohn 这种不是0.5倍的也是一种需求吧, 应该会比较常用, 可以考虑纳入实现.
