### ISSUE TITLE
图片轮播控件需求汇总

### ISSUE THREAD

**Issue by deodeng** [ecomfe/moye#44]
come on!

**Comment by deodeng** [comment]
支持的类型：
1. 根据指定的某DOM 
2. 根据传递的数组数据

支持的效果：
1. 渐隐渐现
2. 左右滑动
3. 上下滑动
4. html5 效果（待定）

**Comment by jinzhubaofu** [comment]
来自百度财富的需求: 

1. 当只有一张图片时, 可以隐藏arrow和pager
2. arrow和pager需要比较好的可扩展能力, 比如在pager中的`文字标题`或`小图片预览`, 在`arrow`中使用`iconfont`

![image](https://cloud.githubusercontent.com/assets/811195/6054765/eb289a00-ad2c-11e4-83f4-78fec53bc59a.png)

![image](https://cloud.githubusercontent.com/assets/811195/6054775/058ebf3c-ad2d-11e4-8c88-65de7a9128f4.png)

**Comment by deodeng** [comment]
谢谢，已收到

发件人: leon [mailto:notifications@github.com]
发送时间: 2015年2月5日 11:53
收件人: ecomfe/moye
抄送: Deng,Lingbo
主题: Re: [moye] 图片轮播控件需求汇总 (#44)


来自百度财富的需求:

  1.  当只有一张图片时, 可以隐藏arrow和pager
  2.  arrow和pager需要比较好的可扩展能力, 比如在pager中的文字标题或小图片预览, 在arrow中使用iconfont

[image]<https://cloud.githubusercontent.com/assets/811195/6054765/eb289a00-ad2c-11e4-83f4-78fec53bc59a.png>

[image]<https://cloud.githubusercontent.com/assets/811195/6054775/058ebf3c-ad2d-11e4-8c88-65de7a9128f4.png>
