### ISSUE TITLE
分页控件 Pager  需求汇总

### ISSUE THREAD

**Issue by mySunShinning** [ecomfe/moye#45]

**Comment by mySunShinning** [comment]
保障分页

**Comment by mySunShinning** [comment]
保障分页
![baozhang](https://cloud.githubusercontent.com/assets/9652870/6102825/79a75562-b077-11e4-8fb7-8ee39208f5b9.png)

**Comment by mySunShinning** [comment]
百度健康
1、列表页
![default](https://cloud.githubusercontent.com/assets/9652870/6102963/4f7d69b4-b079-11e4-868b-07beab6b51f7.png)
2、二级页面卡片
![default](https://cloud.githubusercontent.com/assets/9652870/6102966/59046cbc-b079-11e4-982b-d40900d3eb58.png)

百度教育
![default](https://cloud.githubusercontent.com/assets/9652870/6102976/720b2372-b079-11e4-8721-c7c3c16ede6e.png)

百度汽车
![default](https://cloud.githubusercontent.com/assets/9652870/6102979/7b6293f6-b079-11e4-89ac-4fdfc4709f99.png)

百度财富
![default](https://cloud.githubusercontent.com/assets/9652870/6102984/8c80ccd4-b079-11e4-96aa-630efbecbfdf.png)

百度个人中心
![default](https://cloud.githubusercontent.com/assets/9652870/6102987/98819428-b079-11e4-80a4-c0fcd477a0f0.png)

**Comment by mySunShinning** [comment]
需求汇总

1、基本功能
    - 支持皮肤切换
    - 状态：正常/鼠标浮动/选中状态/不可点
    - 文案修改
    - 跳转到第n页

2、扩展功能
    - 精简版pager
![59046cbc-b079-11e4-982b-d40900d3eb58](https://cloud.githubusercontent.com/assets/9652870/6104435/698556e6-b088-11e4-9470-a2a25aa72250.png)
    - 只提供事件处理

**Comment by mySunShinning** [comment]
基本功能的4点，目前moye/Pager已经提供

**Comment by mySunShinning** [comment]
本次需要开发的最小功能：扩展功能中的1、2

只提供事件处理，后续排期

**Comment by mySunShinning** [comment]
# Pager属性与方法定义

### 属性
```
{
    {number} page: 0,  // 当前页码
    {number} first: 0,  // 起始页码
    {number} padding: 1, // 收尾显示的页码个数
    {boolean} showAlways: true, // 是否一直显示分页
    {number} showCount: 5, // 当页数较多时，中间显示页码的个数
    {number} total: 10, // 总页数
    {string} disabledClass: 'disabled', // 分页项不用可时的class定义
    {Object} lang: {
        {string} prev: '上一页',
        {string} next: '下一页',
        {string} ellipsis: '...'
    },

    // 需要添加属性
    {boolean} anchor: true, // 是锚点
    {string} url: 'http://xxx.png' // 跳转地址
}
```

### 接口
1. setPage({number} page) // 设置页码
2. {number} getPage()  // 返回当前页码
3. setTotal({number} total)  // 设置总页数
4. {number} getTotal()  // 获取总页数

### 事件
1. `change`

// 后续未完

**Comment by michaelliu90316** [comment]
样式需求

百度口碑：[http://koubei.baidu.com/s/baidu.com?page=3&tab=comt]()
---
![pager](https://cloud.githubusercontent.com/assets/1811842/6108442/35c14132-b0ae-11e4-9ed5-d376fb94f238.png)
