### ISSUE TITLE
Moye2.0 RoadMap讨论

### ISSUE THREAD

**Issue by jinzhubaofu** [ecomfe/moye#49]
整理了一下本次2.0版本需要完成的功能：

1. 基于jQuery的重构
2. 支持皮肤、状态
3. 支持插件
4. 拆分lib库
5. 新的控件生命周期机制
6. 新的demo站点
7. 新的全局api: `moye.create()` / `moye.get()` / `moye.init()`
8. 新的控件：Form / Tag等等
9. 与ecomui相一致的api设计
10. 新的`less`编写模式，提供大量的预置变量，以提供灵活的样式自定义调整
11. smarty预渲染模板

在之前一段时间里我们已经完成了其中的绝大部分开发工作，接下来我们的几个迭代将要继续完成的工作：

1. 完成smarty预渲染模板的开发 预计时间：0309 ~ 0322
2. 完成单测的编写 预计时间：0323 ~ 0405
3. 完成基于jsdoc3的api文档编写与生成 预计时间：0406 ~ 0419
4. 视觉设计标准化 预计时间：0406 ~ 0419

大家看是否OK，如有遗漏请大家补充。

**Comment by michaelliu90316** [comment]
得预留手工测试的时间吧

**Comment by jinzhubaofu** [comment]
@michaelliu90316 唔，正式发布前留一到两周做整体的回归和细节微调吧。
