### ISSUE TITLE
Form控件需求汇总

### ISSUE THREAD

**Issue by wuhy** [ecomfe/moye#52]
## 需求

* 支持表单提交自动校验
* 获取表单提交信息

## 属性

* {string} action 提交表单 action，可选，默认 空，即当前页面
* {string} method 提交表单 method，可选，默认 GET
* {string} target 提交表单 target, 可选, 默认 _self
 

## 接口

* {Array} getInputControls(): 获取表单输入控件 
* {Object} getData(): 获取表单提交的 `输入控件` 的数据，以 `name` 为键，以 `value` 为值
* {boolean|Promise} validate(): 验证表单数据有效性，自动触发所有`输入控件`的`validate`方法，如果校验通过返回true，如果校验是个异步过程，则返回 `Promise` ，校验完成，触发 `done` 回调，回调参数值为校验结果的 boolean 值
* {Form} submit(): 提交表单
 

## 事件

* submit: 提交表单，触发的事件，可以通过e.preventDefault()方式阻止表单默认提交方式，通过该方式可以自行实现自己的提交方式比如发送ajax方式

**Comment by jinzhubaofu** [comment]
还需要一个`checkValidity()`接口，只校验当前输入是否合法，不触发校验相关的事件，比如：`beforevalidate` / `validateing` / `valid` / `invalid`。
