### ISSUE TITLE
.extend 创建类中的 parent 问题

### ISSUE THREAD

**Issue by mescoda** [ecomfe/moye#56]
用 `.extend` 创建的多层子类中，使用 `.parent(name)` 调用父类中方法时，会因为 `this` 一直是新建出来的实例，造成死循环的问题。

解决方法：

1. [Prototype 中的重写方法，被 John Resig 借鉴过](http://ejohn.org/blog/simple-javascript-inheritance/)

2. [最早可能是 mootools 中的利用 augments.callee.caller](https://github.com/mootools/mootools-core/blob/master/Source/Class/Class.js)

**Comment by jinzhubaofu** [comment]
目前我们只支持一层`extend`。

在`feature/ng`分支上，是支持多层`extend`的，源码是在[这里](https://github.com/ecomfe/moye/blob/feature/ng/src/ui/lib/class.js#L97)。

另外，在这个分支上，`.parent(name)`方法的实现也做了简化，并更新为`.$parent(...)`。实现方案是你提到的2

**Comment by mescoda** [comment]
了解了
多谢
