### ISSUE TITLE
[Popup] static模式下处理window.resize事件

### ISSUE THREAD

**Issue by jinzhubaofu** [ecomfe/moye#61]
现在`static`模式下，`popup`在`window`的`resize`时不会自动重新定位。这样会导致一些问题。

@michaelliu90316 添加这部分的功特性，会不会影响其他的功能？没有的话我就添加一下。

**Comment by michaelliu90316** [comment]
可以添加的，去掉 `mode` 判断即可，之前只在 `over` 和 `click` 模式下处理了resize。

**Comment by jinzhubaofu** [comment]
OK done
