### ISSUE TITLE
[Mask] Mask在IE8下只有鼠标移到Dialog外才会显示

### ISSUE THREAD

**Issue by cxtom** [ecomfe/moye#74]
如何复现：

浏览器：IE8
打开Dialog会弹出Mask，如果Dialog很大，可能在初始状态下鼠标是在Dialog里面的，这时候Mask就没有显示，需要移动到Dialog外面才会显示

**Comment by jinzhubaofu** [comment]
在2.0.5版本中修复了这个问题。
